export const communityProfile = {
  name: "Daddy Gaming Lobby",
  members: 12847,
  membersFormatted: "12,847",
  membersCompact: "12.8K",
  messagesPerDay: 43281,
  messagesPerDayFormatted: "43,281",
  messagesPerHourFormatted: "1.8K",
  voiceHoursPerWeek: 1284,
  voiceHoursPerWeekFormatted: "1,284",
  monthlyGrowth: 8.7,
  monthlyGrowthFormatted: "+8.7%",
  retention: 78,
  retentionFormatted: "78%",
  healthScore: 87,
  insightsGenerated: 147,
  recommendationsGenerated: 23,
  weeklyMessagesFormatted: "303K",
  healthChange: "+2.1%",
} as const;
